### ISSUE TITLE
希望添加多知识库快捷切换功能

### ISSUE THREAD

**Issue by leozhudd** [Juexe/YuqueSync#3]
楼主辛苦了，感谢您开发了这么好用的同步插件，2022年了依旧可以使用！

我拥有多个知识库，都需要做同步，这个插件目前切换知识库必须进入插件设置界面更换namespace，每换一个知识库都要重新设置一遍，而且无法持久保存多个namespace的信息，较为麻烦。
由于我不会php开发，难以修改，希望楼主有时间可以增加多知识库同步的feature～

Thanks！

**Comment by Juexe** [comment]
这个需求挺好，近期会更新一下

**Comment by Juexe** [comment]
已经支持可以在 post 界面修改 `namespace`，可以手动 pull 一下代码

**Comment by Juexe** [comment]
@leozhudd 做了进一步更新（v1.2），现在只需要下拉选择想要同步的文档即可，具体效果可以看看 README 底下动图。
重点：代码更新后，需要到插件管理中重启一下插件，再配置一下 token 就行。

**Comment by leozhudd** [comment]
> 

非常强！试了很好用66666
我本来也想说能不能有直接下拉选择，但怕你工作量太大😂大佬nb🎉

**Comment by leozhudd** [comment]
生成的文章链接的格式有问题：
let link = `https://www.yuque.com/${namespace}/${slug}`;
缺了一项{username}吧？🤔

**Comment by Juexe** [comment]
草率了，忘了拼 username。v1.2.1 已经 fixed

> 生成的文章链接的格式有问题： let link = `https://www.yuque.com/${namespace}/${slug}`; 缺了一项{username}吧？🤔
